export const ADD_CAREER = 'ADD_CAREER'
export const FETCH_CAREER_REQUEST = 'FETCH_CAREER_REQUEST'
export const FETCH_CAREER_SUCCESS = 'FETCH_CAREER_SUCCESS'
export const FETCH_CAREER_FAILURE = 'FETCH_CAREER_FAILURE'