export const ADD_CAREER = 'ADD_CAREER'
export const FETCH_CAREER_REQUEST = 'FETCH_CAREER_REQUEST'
export const FETCH_CAREER_SUCCESS = 'FETCH_CAREER_SUCCESS'
export const FETCH_CAREER_FAILURE = 'FETCH_CAREER_FAILURE'
export const CHANGE_MAIN_CAREER = 'CHANGE_MAIN_CAREER'
export const GET_CAREER_LIST_SUCCESS = 'GET_CAREER_LIST_SUCCESS';
export const GET_CAREER_LIST_FAILURE = 'GET_CAREER_LIST_FAILURE';