export const ADD_COLLEGE = 'ADD_COLLEGE'
export const FETCH_COLLEGE_REQUEST = 'FETCH_COLLEGE_REQUEST'
export const FETCH_COLLEGE_SUCCESS = 'FETCH_COLLEGE_SUCCESS'
export const FETCH_COLLEGE_FAILURE = 'FETCH_COLLEGE_FAILURE'