export const ADD_COURSE = 'ADD_COURSE'
export const FETCH_COURSE_REQUEST = 'FETCH_COURSE_REQUEST'
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS'
export const FETCH_COURSE_FAILURE = 'FETCH_COURSE_FAILURE'
